name: testssh

on:
  push:
    branches:
      - main

jobs:

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
          
      - name: testssh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          mkdir ~/test
          cd test
          cho "hello from server" > hello.txt
          cat hello.txt
