name: testssh

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
          
      - name: testssh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
        run: |
          echo "hello from server $SSH_HOST" > hello.txt
          cat hello.txt
